### ISSUE TITLE
Dialog "compressing ... Success" is not closeable with Escape key

### ISSUE THREAD

**Issue by vn971** [prati0100/git-gui#17]
It would be very convenient if this dialog would be closable with just Escape key.
![2019 11 29_10:36:20](https://user-images.githubusercontent.com/1547617/69859274-18dfc780-1294-11ea-9006-2683add064e8.png)

Additionally and independently, it would be nice for the dialog before that to be closable with Escape, and maybe that Enter would act as "OK".

**Comment by prati0100** [comment]
Shouldn't be something too difficult to implement. I'll come up with a patch in a couple days.

**Comment by prati0100** [comment]
> It would be very convenient if this dialog would be closable with just Escape key.

Patch for this submitted [here](https://lore.kernel.org/git/20191206222040.toj4enbbbbamnrww@yadavpratyush.com/)

> Additionally and independently, it would be nice for the dialog before that to be closable with Escape, and maybe that Enter would act as "OK".

Which dialog are you talking about? Is it the one mentioned [here](https://lore.kernel.org/git/CAGr--=K15nUcnsJWOP87uMMjeQmTgAeO_6hnr12k2zuNQjNyBw@mail.gmail.com/)? If yes, then this dialog will soon be removed. In fact, I have a half cooked fix for it over at https://github.com/prati0100/git-gui/tree/py/auto-gc which I will finish up soon.

**Comment by vn971** [comment]
Yeah, that was the dialog I was talking about. Nice.)

**Comment by prati0100** [comment]
Johannes suggested on the mailing list review thread [here](https://lore.kernel.org/git/nycvar.QRO.7.76.6.1912071723010.31080@tvgsbejvaqbjf.bet/) that Ctrl-W would be a better idea for this than Esc. I agree, but with a slightly different reason [here](https://lore.kernel.org/git/20191208194046.csf35b7rgycst2vc@yadavpratyush.com/).

If you want to supply a counter-argument, please do so on the mailing list thread (and not on this GitHub thread). Otherwise, I'll go ahead with Ctrl-W.

In case you're not subscribed on the list, reply instructions are given at the bottom of these links.

**Comment by prati0100** [comment]
Fixed in https://github.com/prati0100/git-gui/commit/23cbe427c44645a3ab0449919e55bade5eb264bc
