### ISSUE TITLE
add option to disable dark mode (themed widgets)

### ISSUE THREAD

**Issue by martin-weiser-allegro-packets** [prati0100/git-gui#30]
git-gui version 0.21.0.53.g0d211

When running in dark mode on macOS the UI looks pretty broken and e.g. the cursor is not even visible in the commit message text box.

gitk provides an option to enable/disable "Use themed widgets" which allows you to go back to the normal UI despite using dark mode in the rest of the OS. Something like that should be available for git-gui, too.

**Comment by prati0100** [comment]
Hi,

Does setting `gui.usettk` to 0 work for you?

You can do that by running:

`git config gui.usettk 0`

If it does, it might be a good idea to add an option to toggle this in the settings menu.

**Comment by martin-weiser-allegro-packets** [comment]
Thanx for the suggestion but unfortunately it does not make a difference.
I can see that the that the value is set (gui.usettk=0) in 'git config --list' but the application looks and behaves the same.

**Comment by prati0100** [comment]
Do you set the "Use themed widgets" in gitk to yes or no? Make the config variable `gui.usettk` reflect that value. So, if you choose "Use themed widgets" as yes, then set `gui.usettk` to 1 and vice versa.

Since both gitk and git-gui use very similar mechanisms for theming (ttk), their behaviour should be largely the same. If this doesn't work for you, can you send screenshots of both git-gui and gitk with ttk enabled and disabled?

**Comment by martin-weiser-allegro-packets** [comment]
I disabled "Use themed widgets" in gitk.

Actually setting gui.usettk did change the appearance of git-gui slightly, which I did not notice before. But it does not fix the issue of a strange appearance and the cursor not being visible.

This is gitk with "Use themed widgets" enabled:

![gitk-themed](https://user-images.githubusercontent.com/20415987/74818835-a6650d80-52ff-11ea-9fa7-df1f6afe113e.jpg)

This is gitk with "Use themed widgets" disabled:

![gitk-not-themed](https://user-images.githubusercontent.com/20415987/74818876-bed52800-52ff-11ea-9df2-fd4412db9ac6.jpg)


This is git-gui with gui.usettk=1

![git-gui-ttk-1](https://user-images.githubusercontent.com/20415987/74818927-d1e7f800-52ff-11ea-99a5-1dc826b4985d.jpg)


This is git-gui with gui.usettk=0

![git-gui-ttk-0](https://user-images.githubusercontent.com/20415987/74818944-d8766f80-52ff-11ea-8bda-35bab6fe630c.jpg)


And this is git-gui when I set macOS to light mode:

![git-gui-light](https://user-images.githubusercontent.com/20415987/74818993-ea581280-52ff-11ea-9ee4-3a3d7c2dcec4.jpg)

**Comment by prati0100** [comment]
@last-partizan sent out a patch to add basic dark mode support for git-gui that can be found [here](https://github.com/prati0100/git-gui/commit/dbcafc2560fa0ef7a8dabe2a004d54027be34ee5). Can you please test it and see if it works for you?

**Comment by last-partizan** [comment]
My main OS is Linux, but i've had an opportunity to test this on mac.

<img width="933" alt="Screenshot 2020-09-26 at 16 12 04" src="https://user-images.githubusercontent.com/301015/94341585-35af6d80-0013-11eb-995f-ff66134f5526.png">

My patch indeed fixes invisible cursor, but i need to do this,

```
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
```

otherwise theme was not applied and fonts was looking horrible.

I still working on sending this patch to maillist, but you can check it here: https://github.com/last-partizan/git-gui/tree/dark-colors

**Comment by last-partizan** [comment]
I think this issue must be closed, as "adding option to disable dark mode" is workaround, and proper way is to fix a bug #39.

**Comment by prati0100** [comment]
Closing. #39 should fix this problem too.
