### ISSUE TITLE
commit message text cursor missing in dark theme for macOS

### ISSUE THREAD

**Issue by lormanlau** [prati0100/git-gui#39]
The text cursor when typing in a commit message is not visible while in dark theme.
In light theme the cursor blinks and shows normally. I suspect that the cursor is blinking white.

macOS Catalina 10.15.6
git-gui version 0.21.0.72.g46972
git version 2.28.0

Tcl/Tk version 8.6.10

<img width="465" alt="Screen Shot 2020-07-29 at 10 01 43 AM" src="https://user-images.githubusercontent.com/12117112/88830310-a60c5080-d182-11ea-8d51-cefac6fa6e6b.png">

<img width="467" alt="Screen Shot 2020-07-29 at 10 02 06 AM" src="https://user-images.githubusercontent.com/12117112/88830328-aa386e00-d182-11ea-966f-ae7dac9e8885.png">

**Comment by prati0100** [comment]
Seems related to #30. I unfortunately don't have a lot of free time so I can't say for sure when I can get around to looking at it.

**Comment by last-partizan** [comment]
@lormanlau 

https://github.com/last-partizan/git-gui/tree/dark-colors

Please check if this branch fixed bug for you.

**Comment by prati0100** [comment]
Should be fixed with https://github.com/prati0100/git-gui/commit/01121d6132135e62d4bf7c2e67e749ae3037d0ba. If you still see the issue please feel free to reopen.

**Comment by Airblader** [comment]
@prati0100 From my understanding you're now pulling colors from the Xresources without specifying the actual client class, but using a wildcard instead. This is very unfortunately common in the X world, but nonetheless not how the resource database is intended to work as it makes app-specific theming impossible. git-gui should instead specify a concrete value (by convention its WM_CLASS) instead of the wildcard.

On a side note, I think this change "broke" my setup because my previous light git-gui suddenly turned dark theme and the cursor is (still) gone (on Linux), though I haven't bisected it.
